import Section from '../components/ui/Section';
import Breadcrumbs from '../components/ui/Breadcrumbs';
import { Heading } from '../components/ui/Heading';
import { Text } from '../components/ui/Text';
import SEO from '../components/SEO';
import { Banner } from '@bettergov/kapwa/banner';
import { Card, CardContent } from '@bettergov/kapwa/card';
import { Input } from '@bettergov/kapwa/input';
import { Search as SearchIcon } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { useEffect, useState } from 'react';

interface PagefindResultData {
  url: string;
  excerpt: string;
  meta: { title?: string; category?: string };
  filters: { section?: string[] };
}

interface Pagefind {
  debouncedSearch: (
    term: string,
    options?: object,
    timeout?: number
  ) => Promise<{
    results: { id: string; data: () => Promise<PagefindResultData> }[];
  } | null>;
}

const MAX_RESULTS = 20;

// Generated by `npm run search:index` into public/pagefind
const pagefindPath = `${import.meta.env.BASE_URL}pagefind/pagefind.js`;
let pagefindPromise: Promise<Pagefind> | null = null;

function loadPagefind(): Promise<Pagefind> {
  // An absolute URL stops the Vite dev server from rewriting the import
  // (it would append ?import and fail to serve the file from /public)
  const pagefindUrl = new URL(pagefindPath, window.location.origin).href;
  pagefindPromise ??= import(/* @vite-ignore */ pagefindUrl);
  return pagefindPromise;
}

export default function Search() {
  const [searchParams, setSearchParams] = useSearchParams();
  const query = searchParams.get('q') ?? '';
  const [results, setResults] = useState<PagefindResultData[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const term = query.trim();
    if (!term) {
      setResults([]);
      setLoading(false);
      return;
    }

    let cancelled = false;
    setLoading(true);

    loadPagefind()
      .then(pagefind => pagefind.debouncedSearch(term, {}, 200))
      .then(async search => {
        // null means a newer search superseded this one
        if (!search || cancelled) return;
        const data = await Promise.all(
          search.results.slice(0, MAX_RESULTS).map(result => result.data())
        );
        if (cancelled) return;
        setResults(data);
        setError(null);
        setLoading(false);
      })
      .catch(err => {
        if (cancelled) return;
        console.error('Search failed', err);
        setError('Search is unavailable right now. Please try again later.');
        setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [query]);

  const handleChange = (value: string) => {
    setSearchParams(value ? { q: value } : {}, { replace: true });
  };

  return (
    <>
      <SEO
        title="Search"
        description={`Search services, offices and information from the ${import.meta.env.VITE_GOVERNMENT_NAME} government.`}
      />
      <Section className="p-3 mb-12">
        <Breadcrumbs className="mb-8" />
        <Heading>Search</Heading>
        <Text className="text-gray-600 mb-6">
          Find services, offices and government information.
        </Text>

        <form
          role="search"
          className="relative mb-8"
          onSubmit={e => e.preventDefault()}
        >
          <SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-gray-400 pointer-events-none" />
          <Input
            type="search"
            aria-label="Search the site"
            placeholder="e.g. business permit, birth certificate, garbage collection"
            className="pl-10"
            value={query}
            onChange={e => handleChange(e.target.value)}
            autoFocus
          />
        </form>

        {error && <Banner type="error" description={error} icon />}

        {!error && query.trim() && !loading && results.length === 0 && (
          <Text className="text-gray-600">
            No results for &ldquo;{query.trim()}&rdquo;.
          </Text>
        )}

        {!error && results.length > 0 && (
          <div className="space-y-4" aria-busy={loading}>
            {results.map(result => (
              <Link key={result.url} to={result.url} className="block">
                <Card hoverable>
                  <CardContent>
                    <h4 className="text-lg font-medium text-gray-900">
                      {result.meta.title}
                    </h4>
                    <p
                      className="mt-2 text-sm text-gray-600 [&_mark]:bg-yellow-100 [&_mark]:text-gray-900"
                      dangerouslySetInnerHTML={{ __html: result.excerpt }}
                    />
                    <div className="mt-2 flex flex-wrap gap-2">
                      {[result.filters.section?.[0], result.meta.category]
                        .filter(Boolean)
                        .map(label => (
                          <span
                            key={label}
                            className="inline-block px-2 py-1 text-xs font-medium rounded-sm bg-gray-100 text-gray-800"
                          >
                            {label}
                          </span>
                        ))}
                    </div>
                  </CardContent>
                </Card>
              </Link>
            ))}
          </div>
        )}
      </Section>
    </>
  );
}
