import Section from '../components/ui/Section';
import Breadcrumbs from '../components/ui/Breadcrumbs';
import { Heading } from '../components/ui/Heading';
import { Text } from '../components/ui/Text';
import SEO from '../components/SEO';
import {
  serviceCategories,
  governmentCategories,
  getCategorySubcategories,
  type Category,
  type Subcategory,
} from '../data/yamlLoader';
import { Link } from 'react-router-dom';
import { useEffect, useState } from 'react';

const sections = [
  { label: 'Services', path: 'services', data: serviceCategories },
  { label: 'Government', path: 'government', data: governmentCategories },
];

// Generated by `npm run llm:build` into public/
const machineReadableFiles = ['sitemap.xml', 'llms.txt', 'llms-full.txt'];

type PagesByCategory = Record<string, Subcategory[]>;

function CategoryLinks({
  path,
  category,
  pages,
}: {
  path: string;
  category: Category;
  pages: Subcategory[];
}) {
  return (
    <div>
      <Link
        to={`/${path}/${category.slug}`}
        className="text-lg font-semibold text-gray-900 hover:text-primary-600"
      >
        {category.category}
      </Link>
      {pages.length > 0 && (
        <ul className="mt-2 space-y-1 border-l border-gray-200 pl-4">
          {pages.map(page => (
            <li key={page.slug}>
              <Link
                to={`/${path}/${category.slug}/${page.slug}`}
                className="text-sm text-gray-600 hover:text-primary-600"
              >
                {page.name}
              </Link>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

export default function Sitemap() {
  const [pages, setPages] = useState<PagesByCategory>({});

  useEffect(() => {
    const keys = sections.flatMap(section =>
      section.data.categories.map(category => category.slug)
    );
    Promise.all(keys.map(getCategorySubcategories))
      .then(indexes =>
        setPages(
          Object.fromEntries(keys.map((key, i) => [key, indexes[i].pages]))
        )
      )
      .catch(console.error);
  }, []);

  return (
    <>
      <SEO
        title="Sitemap"
        description={`Every service and government page on the ${import.meta.env.VITE_GOVERNMENT_NAME} portal.`}
      />
      <Section className="p-3 mb-12">
        <Breadcrumbs className="mb-8" />
        <Heading>Sitemap</Heading>
        <Text className="text-gray-600 mb-8">
          Every service and government page on this site.
        </Text>

        {sections.map(section => (
          <div key={section.path} className="mb-10">
            <Heading level={2}>
              <Link to={`/${section.path}`} className="hover:text-primary-600">
                {section.label}
              </Link>
            </Heading>
            <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
              {section.data.categories.map(category => (
                <CategoryLinks
                  key={category.slug}
                  path={section.path}
                  category={category}
                  pages={pages[category.slug] ?? []}
                />
              ))}
            </div>
          </div>
        ))}

        <Text size="sm" className="text-gray-500">
          For search engines and AI tools:{' '}
          {machineReadableFiles.map((file, i) => (
            <span key={file}>
              {i > 0 && ', '}
              <a href={`/${file}`} className="underline hover:text-primary-600">
                {file}
              </a>
            </span>
          ))}
        </Text>
      </Section>
    </>
  );
}
